#include "autotune_entry.hpp"

#include "autotune_manager.hpp"
#include "autotune_persist.hpp"
#include "autotune_runner.hpp"
#include "autotune_types.hpp"

#include "n0s/misc/console.hpp"
#include "n0s/params.hpp"
#include "n0s/version.hpp"

#include <set>
#include <sstream>
#include <string>

namespace n0s
{
namespace autotune
{

namespace
{

/// Parse comma-separated GPU indices from string
std::set<uint32_t> parseGpuIndices(const std::string& str)
{
	std::set<uint32_t> indices;
	if(str.empty()) return indices;

	std::istringstream ss(str);
	uint32_t idx;
	while(ss >> idx)
	{
		indices.insert(idx);
		while(ss.peek() == ',' || ss.peek() == ' ')
			ss.ignore();
	}
	return indices;
}

TuneMode parseTuneMode(const std::string& str)
{
	if(str == "quick") return TuneMode::Quick;
	if(str == "exhaustive") return TuneMode::Exhaustive;
	return TuneMode::Balanced;
}

TuneTarget parseTuneTarget(const std::string& str)
{
	if(str == "efficiency") return TuneTarget::Efficiency;
	if(str == "balanced") return TuneTarget::Balanced;
	return TuneTarget::Hashrate;
}

/// Write the winning AMD candidate to the amd.txt config
bool writeAmdConfig(uint32_t device_index, const AmdCandidate& winner, const std::string& config_path)
{
	FILE* f = fopen(config_path.c_str(), "w");
	if(!f) return false;

	fprintf(f, "// Generated by n0s-ryo-miner --autotune\n");
	fprintf(f, "// Device %u: intensity=%zu worksize=%zu\n\n", device_index, winner.intensity, winner.worksize);
	fprintf(f, "\"gpu_threads_conf\" : [\n");
	fprintf(f, "  { \"index\" : %u,\n", device_index);
	fprintf(f, "    \"intensity\" : %zu, \"worksize\" : %zu,\n", winner.intensity, winner.worksize);
	fprintf(f, "    \"affine_to_cpu\" : false, \"strided_index\" : 0, \"mem_chunk\" : 2,\n");
	fprintf(f, "    \"unroll\" : 1, \"comp_mode\" : true, \"interleave\" : 40\n");
	fprintf(f, "  },\n");
	fprintf(f, "],\n\n");
	fprintf(f, "\"auto_tune\" : 0,\n");
	fprintf(f, "\"platform_index\" : 0,\n");
	fclose(f);

	printer::inst()->print_msg(L0, "AUTOTUNE: AMD config written to %s", config_path.c_str());
	return true;
}

/// Write the winning NVIDIA candidate to the nvidia.txt config
bool writeNvidiaConfig(uint32_t device_index, const NvidiaCandidate& winner, const std::string& config_path)
{
	FILE* f = fopen(config_path.c_str(), "w");
	if(!f) return false;

	fprintf(f, "// Generated by n0s-ryo-miner --autotune\n");
	fprintf(f, "// Device %u: threads=%u blocks=%u bfactor=%u\n\n",
		device_index, winner.threads, winner.blocks, winner.bfactor);
	fprintf(f, "\"gpu_threads_conf\" :\n[\n");
	fprintf(f, "  { \"index\" : %u,\n", device_index);
	fprintf(f, "    \"threads\" : %u, \"blocks\" : %u,\n", winner.threads, winner.blocks);
	fprintf(f, "    \"bfactor\" : %u, \"bsleep\" : 0,\n", winner.bfactor);
	fprintf(f, "    \"affine_to_cpu\" : false, \"sync_mode\" : 3,\n");
	fprintf(f, "    \"mem_mode\" : 1,\n");
	fprintf(f, "  },\n");
	fprintf(f, "],\n");
	fclose(f);

	printer::inst()->print_msg(L0, "AUTOTUNE: NVIDIA config written to %s", config_path.c_str());
	return true;
}

} // anonymous namespace

int do_autotune()
{
	auto& p = params::inst();

	printer::inst()->print_msg(L0, "");
	printer::inst()->print_msg(L0, "╔══════════════════════════════════════════╗");
	printer::inst()->print_msg(L0, "║       n0s-ryo-miner AUTOTUNE            ║");
	printer::inst()->print_msg(L0, "║  Finding optimal GPU settings...         ║");
	printer::inst()->print_msg(L0, "╚══════════════════════════════════════════╝");
	printer::inst()->print_msg(L0, "");

	// Build config from params
	AutotuneConfig config;
	config.mode = parseTuneMode(p.autotune_mode);
	config.target = parseTuneTarget(p.autotune_target);
	config.backend_filter = p.autotune_backend;
	config.gpu_indices = parseGpuIndices(p.autotune_gpus);
	config.reset = p.autotune_reset;
	config.resume = p.autotune_resume;
	config.benchmark_seconds = p.autotune_benchmark_sec;
	config.stability_seconds = p.autotune_stability_sec;
	config.autotune_file = p.autotune_file;

	printer::inst()->print_msg(L0, "AUTOTUNE: Mode=%s Target=%s Backend=%s Benchmark=%ds Stability=%ds",
		p.autotune_mode.c_str(), p.autotune_target.c_str(), p.autotune_backend.c_str(),
		config.benchmark_seconds, config.stability_seconds);

	// Find the miner binary path
	std::string miner_path = p.minerArg0;
	if(miner_path.empty())
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: ERROR — cannot determine miner binary path");
		return 1;
	}

	SubprocessRunner runner(miner_path);
	AutotuneManager manager(config);

	bool any_success = false;

	// AMD/OpenCL devices
	bool tune_amd = (config.backend_filter == "all" || config.backend_filter == "amd");
	bool tune_nvidia = (config.backend_filter == "all" || config.backend_filter == "nvidia");

#ifndef CONF_NO_OPENCL
	if(tune_amd && p.useAMD)
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: Scanning AMD/OpenCL devices...");

		// Discover AMD GPUs — for now support single GPU (index 0)
		// TODO: Multi-GPU discovery via clinfo or backend query
		std::vector<uint32_t> amd_devices;
		if(config.gpu_indices.empty())
			amd_devices.push_back(0); // Default: GPU 0
		else
		{
			for(auto idx : config.gpu_indices)
				amd_devices.push_back(idx);
		}

		for(uint32_t dev_idx : amd_devices)
		{
			DeviceFingerprint fp;
			if(!runner.collectAmdFingerprint(dev_idx, fp))
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: Failed to collect fingerprint for AMD GPU %u", dev_idx);
				continue;
			}

			printer::inst()->print_msg(L0, "AUTOTUNE: AMD GPU %u: %s (%u CUs, %zu MiB VRAM)",
				dev_idx, fp.gpu_name.c_str(), fp.compute_units,
				fp.vram_bytes / (1024 * 1024));

			// Create evaluator callback
			auto evaluator = [&runner](uint32_t device_index, const CandidateRecord& candidate,
				int benchmark_sec, BenchmarkMetrics& metrics) -> bool {
				return runner.evaluateAmd(device_index, candidate, benchmark_sec, metrics);
			};

			const CandidateRecord* best = manager.tuneDevice(dev_idx, fp, evaluator);
			if(best)
			{
				writeAmdConfig(dev_idx, best->amd, p.configFileAMD);
				any_success = true;
			}
		}
	}
#endif

#ifndef CONF_NO_CUDA
	if(tune_nvidia && p.useNVIDIA)
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: Scanning NVIDIA/CUDA devices...");

		std::vector<uint32_t> nv_devices;
		if(config.gpu_indices.empty())
			nv_devices.push_back(0); // Default: GPU 0
		else
		{
			for(auto idx : config.gpu_indices)
				nv_devices.push_back(idx);
		}

		for(uint32_t dev_idx : nv_devices)
		{
			DeviceFingerprint fp;
			if(!runner.collectNvidiaFingerprint(dev_idx, fp))
			{
				printer::inst()->print_msg(L0, "AUTOTUNE: Failed to collect fingerprint for NVIDIA GPU %u", dev_idx);
				continue;
			}

			printer::inst()->print_msg(L0, "AUTOTUNE: NVIDIA GPU %u: %s (%s, %u SMs, %zu MiB VRAM)",
				dev_idx, fp.gpu_name.c_str(), fp.gpu_architecture.c_str(),
				fp.compute_units, fp.vram_bytes / (1024 * 1024));

			auto evaluator = [&runner](uint32_t device_index, const CandidateRecord& candidate,
				int benchmark_sec, BenchmarkMetrics& metrics) -> bool {
				return runner.evaluateNvidia(device_index, candidate, benchmark_sec, metrics);
			};

			const CandidateRecord* best = manager.tuneDevice(dev_idx, fp, evaluator);
			if(best)
			{
				writeNvidiaConfig(dev_idx, best->nvidia, p.configFileNVIDIA);
				any_success = true;
			}
		}
	}
#endif

	// Save final results
	const auto& result = manager.getResult();
	saveAutotuneResult(result, config.autotune_file);

	// Optional export
	if(!p.autotune_export.empty())
	{
		saveAutotuneResult(result, p.autotune_export);
		printer::inst()->print_msg(L0, "AUTOTUNE: Results exported to %s", p.autotune_export.c_str());
	}

	if(any_success)
	{
		printer::inst()->print_msg(L0, "");
		printer::inst()->print_msg(L0, "╔══════════════════════════════════════════╗");
		printer::inst()->print_msg(L0, "║       AUTOTUNE COMPLETE ✓                ║");
		printer::inst()->print_msg(L0, "║  Config files written. Run without       ║");
		printer::inst()->print_msg(L0, "║  --autotune to start mining.             ║");
		printer::inst()->print_msg(L0, "╚══════════════════════════════════════════╝");
		return 0;
	}
	else
	{
		printer::inst()->print_msg(L0, "AUTOTUNE: No GPU was successfully tuned.");
		return 1;
	}
}

} // namespace autotune
} // namespace n0s
