#!/usr/bin/env bash
# Generate embedded_assets.hpp from gui/ files
# Usage: embed_assets.sh <gui_dir> <output_hpp>
#
# For each file in gui/, gzip it and convert to a C++ constexpr array.
# Serves pre-compressed with Content-Encoding: gzip for zero runtime cost.

set -euo pipefail

GUI_DIR="${1:?Usage: embed_assets.sh <gui_dir> <output_hpp>}"
OUTPUT="${2:?Usage: embed_assets.sh <gui_dir> <output_hpp>}"

# Temporary dir for gzipped files
TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

cat > "$OUTPUT" <<'HEADER'
#pragma once
// Auto-generated by scripts/embed_assets.sh — DO NOT EDIT
// Gzipped web assets for the N0S-RYO dashboard

#include <cstddef>
#include <cstdint>

namespace n0s {
namespace gui {

struct EmbeddedAsset {
    const char* path;           // URL path (e.g., "/gui/index.html")
    const char* content_type;   // MIME type
    const uint8_t* data;        // Gzipped content
    size_t size;                // Size of gzipped content
};

HEADER

# Process each file
ASSETS=()
for f in "$GUI_DIR"/index.html "$GUI_DIR"/style.css "$GUI_DIR"/app.js; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    varname=$(echo "$base" | sed 's/[^a-zA-Z0-9]/_/g')

    # Gzip
    gzip -9 -c "$f" > "$TMPDIR/$base.gz"

    # Get sizes
    orig_size=$(wc -c < "$f")
    gz_size=$(wc -c < "$TMPDIR/$base.gz")

    # Determine content type
    case "$base" in
        *.html) ctype="text/html; charset=utf-8" ;;
        *.css)  ctype="text/css; charset=utf-8" ;;
        *.js)   ctype="application/javascript; charset=utf-8" ;;
        *)      ctype="application/octet-stream" ;;
    esac

    echo "// $base: $orig_size bytes -> $gz_size bytes gzipped" >> "$OUTPUT"
    echo "static const uint8_t asset_${varname}[] = {" >> "$OUTPUT"

    # Convert to C hex array
    xxd -i < "$TMPDIR/$base.gz" >> "$OUTPUT"

    echo "};" >> "$OUTPUT"
    echo "" >> "$OUTPUT"

    ASSETS+=("${varname}|/gui/${base}|${ctype}")
done

# Write the asset table
cat >> "$OUTPUT" <<'TABLE_START'
static const EmbeddedAsset ASSETS[] = {
TABLE_START

for entry in "${ASSETS[@]}"; do
    IFS='|' read -r varname path ctype <<< "$entry"
    echo "    {\"/gui/$( echo "$path" | sed 's|/gui/||' )\", \"$ctype\", asset_${varname}, sizeof(asset_${varname})}," >> "$OUTPUT"
done

# Also serve root "/" -> index.html
first_var=$(echo "${ASSETS[0]}" | cut -d'|' -f1)
cat >> "$OUTPUT" <<'TABLE_END'
};
static constexpr size_t ASSET_COUNT = sizeof(ASSETS) / sizeof(ASSETS[0]);

} // namespace gui
} // namespace n0s

// Lookup outside the namespace to avoid std:: resolution issues
#include <cstring>
inline const n0s::gui::EmbeddedAsset* n0s_gui_findAsset(const char* path) {
    if (path[0] == '/' && path[1] == '\0') path = "/gui/index.html";
    for (size_t i = 0; i < n0s::gui::ASSET_COUNT; i++) {
        if (strcasecmp(n0s::gui::ASSETS[i].path, path) == 0)
            return &n0s::gui::ASSETS[i];
    }
    return nullptr;
}
TABLE_END

echo "Generated $OUTPUT with ${#ASSETS[@]} assets"
